Feature/auth
sopt-makers/sopt-backend pull request #46
Opened 2023-03-28 16:50 UTC by ozzing

## 📝 PR Summary
유저 인증 및 유저에 관한 API 구현했습니다.
대부분 순차적으로 작성해야 하는 코드들이었는데요, 부득이하게 제가 팀에 혼자라...
PR을 한 번 올리면 다른 분들 확인하시는데 시간이 좀 걸리는 관계로 이렇게 한 PR에 변동사항이 우르르인점 굉장히 죄송하게 생각하고 있습니다...

#### 🌵 Working Branch
feature/auth

#### 🌴 Works
- [x] JWT Token 관련 메소드 구현
- [x] Security 설정
- [x] 모든 API 헤더 Authorization으로 변경
- [x] 닉네임 변경, 탈퇴하기 -> UserController
- [x] 불필요 코드 리팩
- [x] 한마디, 닉네임 조회 / 유저 정보 조회
- [x] 한마디 변경 이사

#### 🌱 Related Issue
#45

2023-03-29 03:55 UTC, bluayer commented
@ozzing 오... 어진님 해당 PR 보려면 최소 순수 시간으로 1~2시간은 필요할 거 같은데 혹시 due date가 언제까지일까요?

2023-03-29 04:02 UTC, ozzing commented
음 목요일 저녁까지 시간되시면 그 안에 되면 더 좋을 것 같아요!
구현해야 할 것이 더 있긴한데, 간단한 중복 검사라 해당 PR에 추가해도 괜찮을까요?

코드 봐주실 때 혼란을 덜기 위해 설명을 더 적자면, 저희 앱팀 개발자 회의를 통해 레거시 제거를 위해 v1 -> v2로 올리기로 했고, 그 과정에서 불필요한 코드(플레이그라운드 소셜 로그인 구현에 따른 기존 인증 로직 등)을 전부 삭제, 이동, 리네이밍해서 pr이 매우매우 커졌습니다.
삭제된 코드는 크게 신경쓰지 않고 보셔도 될 것 같습니다...!

2023-03-30 14:50 UTC, bluayer requested changes
개인적으로는 PR이 길다 보니깐 제가 최대한 집중력을 유지해서 보려고 했음에도 불구하고, 좀 놓치는 부분이 많을 거 같아 아쉽습니다 😥

전반적으로 이 정도 사이즈의 기능을 빠르게 개발하셨다는 점에서 👍 를 드리고 싶은데요, 제가 생각했을 때 조금 아쉬운 점들이 있었습니다.

다음은 제가 코드를 읽으면서 느낀 아쉬운 점입니다. 
- 저번 PR 리뷰 때 val 사용을 권장드렸었고 제 기억으로는 굉장히 잘 지키셨던 것으로 기억하는데, 본 리뷰에서는 auth 관련된 부분이나 user 관련 부분에서 거의 다 해당 부분을 지키지 못한 점이 아쉽습니다... 
- 물론 일정과 시간에 쫓기면서 작성하셨고 PR 사이즈가 커서 그런 것이라고 생각되지만, 저번 코드리뷰 요청 때에 비해 상대적으로 코드 퀄리티가 많이 하락한 부분이 아쉽습니다. 제가 리뷰했던 어진님은 지금보다 더 좋은 코드를 작성하실 수 있는 분이라고 생각되어 특히 더 이런 느낌을 받았던 것 같습니다. 
- major 버전이 한 단계 올라간 것으로 보이는데요, 기존 v1에 대한 지원은 어떻게 되는지(하위호환성 등)에 대해서 PR 관련 설명에 없는 점이 아쉬웠습니다.

분명 일정과 시간에 쫓기는 것은 맞지만, 약간의 시간을 더 들여서 지속될 수 있는 코드를 작성하는 것도 중요하다고 생각합니다. 일반적으로 제가 드리는 리뷰는 권장이고 제가 꼭 다 맞는 것은 아니지만, 이번 리뷰에서는 특히 유의미한 내용들이 있어서 Request Changes를 하겠습니다!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/auth/JwtTokenService.java
> +                        Base64.getEncoder().encodeToString(("" + JWT_SECRET).getBytes(
empty string과 조합을 하는 이유가 따로 있을까요?

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/auth/JwtTokenService.java
> +                        Base64.getEncoder().encodeToString(("" + JWT_SECRET).getBytes(
access token과 refresh token의 secret을 동일하게 가져가는 이유가 있을까요?

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
> +        RestTemplate rt = new RestTemplate();
이렇게 작성하게 되면 매 요청마다 RestTemplate을 만들게 되고... Java의 GC 로직에서 eden space가 금방 꽉차게 되는 상황이 발생하게 됩니다!
차라리 RestTemplate을 필드 멤버로 만들어 주시는 것이 더 좋은 방향일 것 같습니다.
(아니라면, feign 같은 추상화되어 있는 라이브러리를 도입하는 것도 방법입니다.)

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
> +    private ObjectMapper objectMapper;
필드 주입을 하게 되면
1. 객체의 불변성이 보장되지 않아, 런타임에 객체가 바뀔 수 있는 상황이 발생할 수 있음
2. 순환 참조가 일어날 수 있음
같은 문제가 생길 수 있습니다!

따라서 필드 주입은 최대한 배제해주셔야 합니다!!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +            System.out.println(nicknameUser.get().getNickname());
로그로 남기는 부분인걸까요? 가능하다면 slf4j를 사용하거나 로그로 남기는 부분이 아니라면 삭제하는 것이 좋아보입니다!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +    public UserInfo.Id loginWithUserPlaygroundId(AuthResponse.PlaygroundMemberResponse playgroundMemberResponse,
해당 서비스의 메소드들에 @transactional은 의도적으로 생략된 것일까요?

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +        }
userId가 어디서 변동되는지나 그런 부분을 파악하기가 굉장히 어려워보이는데요,  함수로 분리하거나 그런 과정이 필요해보입니다. 지금 상태라면 리팩토링이 너무 까다로울 거 같아요!!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +                    .password("")
서버에서 empty string을 저장해야 할 이유가 있을까요?
자바에서는 보통 객체와 null 때문에 골머리를 썩는데요, empty string까지 추가되면 js를 쓰는 것과 동일한 수준의 어려움을 겪게 될 것 같습니다.
혹시라도 클라이언트와의 응답 때문에 이런 작업이 진행된거라면, 해당 부분을 서버에서 어떻게 관리해야 할지 꼭꼭꼭 생각해보셔야 합니다.

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +                    .nickname(playgroundMemberResponse.getName() + randomNumber)
nickname을 만드는 함수로 분리했다면, random number가 왜 필요한지 읽을 때 고민할 필요가 없었을 것 같습니다!!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/common/config/OpenApiConfig.java
> +                @Server(url = "http://ec2-43-200-170-187.ap-northeast-2.compute.amazonaws.com:8080", description = "개발 환경"),
이렇게 "DNS 이름 + 포트"가 github에 공개되어 버리고, SSL도 적용되어 있지 않다면 보안적으로도 정말 좋지 못합니다...ㅠㅠㅠ (특히 포트 공개가 치명적이고, ec2의 경우에는 private 혹은 public ip가 공개되어 버리기 때문에 이 부분도 굉장한 취약할 수 있습니다. 이렇게 소스코드에 공개되어서 기록이 남았다면, **보통은 인스턴스를 지우고 다시 만들어야 할만큼의 중대한 이슈입니다!!!!**)
해당 부분은 subdomain으로 처리한다던지 이렇게 수정 부탁드립니다!

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
제가 알기로는 `WebSecurityConfigurerAdapter`가 deprecated되어 있다고 알고 있는데 아닐까요??

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/presentation/auth/AuthController.java
> +        val playgroundMember = playgroundAuthService.getPlaygroundMember(playgroundToken.getAccessToken());
해당 정보들이 응집성이 높다면 VO 객체로 묶어서 데리고 다니는 게 맞지 않을까요?
Service 내에서 두 함수를 묶는 함수가 있어도 좋을 것 같습니다.

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/presentation/user/UserController.java
> +    public ResponseEntity<?> withdraw(@AuthenticationPrincipal User user) {
Type에 wildcard를 쓸 이유가 있었던걸까요?

2023-03-30 14:50 UTC, bluayer commented on src/main/java/org/sopt/app/presentation/user/UserResponse.java
> +        @Column(nullable = false)
Response인데 DB에 저장되는 걸까요...? Column이 왜 사용됐는지 궁금합니다.

2023-03-30 15:03 UTC, ozzing commented
먼저 엄청난 사이즈에도 정성스레 리뷰해주신 점 정말 감사드립니다!
말씀해주신 것처럼 시간에 좀 쫓기느라 저도 마음에 들지 않았거나 놓친 부분이 많았는데, 지속될 수 있는 코드를 작성하는 편이 더 좋다는 정우님의 말씀 뒤늦게나마 굉장히 공감되었습니다! 다시 꼼꼼히 확인해보도록 하겠습니다 :)

2023-03-30 15:08 UTC, ozzing commented on src/main/java/org/sopt/app/application/auth/JwtTokenService.java
> +                        Base64.getEncoder().encodeToString(("" + JWT_SECRET).getBytes(
복호화 로직을 하나만 짜둬서 크게 생각해보지 않았던 것 같습니다..!

2023-03-30 15:09 UTC, ozzing commented on src/main/java/org/sopt/app/application/user/UserService.java
> +    public UserInfo.Id loginWithUserPlaygroundId(AuthResponse.PlaygroundMemberResponse playgroundMemberResponse,
놓쳤습니다...

2023-03-30 15:09 UTC, ozzing commented on src/main/java/org/sopt/app/application/user/UserService.java
> +                    .password("")
이 부분은 현재 prod에서 사용하고 있는 필드기에 추후 지울 예정입니다!

2023-03-30 15:09 UTC, ozzing commented on src/main/java/org/sopt/app/application/user/UserService.java
> +                    .nickname(playgroundMemberResponse.getName() + randomNumber)
넵!

2023-03-30 15:09 UTC, ozzing commented on src/main/java/org/sopt/app/common/config/OpenApiConfig.java
> +                @Server(url = "http://ec2-43-200-170-187.ap-northeast-2.compute.amazonaws.com:8080", description = "개발 환경"),
앗 이것도 놓쳤습니다... 죄송합니다ㅠ

2023-03-30 15:17 UTC, ozzing commented on src/main/java/org/sopt/app/application/user/UserService.java
> +            System.out.println(nicknameUser.get().getNickname());
놓쳤습니다...

2023-03-30 16:07 UTC, ozzing commented on src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
이건 더 찾아보겠습니다!

2023-03-30 16:26 UTC, ozzing commented on src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
아 혹시 해당 PR에 위 내용 수정까지 요청하신걸까요??

2023-03-30 16:29 UTC, ozzing commented on src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> +public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
넵 늦은 시간까지 꼼꼼한 리뷰 정말 감사드립니다! 좋은 밤 되세요 😀

2023-03-30 16:34 UTC, merged

2023-03-30 16:44 UTC, bluayer reviewed
하하... 어진님 PR을 빨리 닫고 싶으신 마음은 이해하지만...
보통은 Request Changes라면 리뷰를 재요청하는 것이 일반적입니다.
리뷰가 잘 반영되었는지에 대한 책임은 코드 작성자와 리뷰어가 함께 가지고 있기 때문입니다. 
또한 리뷰를 드렸지만, 컨텍스트가 잘 이해가 되신건지 혹은 더 나은 코드를 작성하셨는지 확인하는 것도 리뷰어가 하는 일입니다.

제가 남긴 리뷰는 다른 PR에서 추가적으로 작업해주시길 바랍니다.

2023-03-30 16:44 UTC, bluayer commented on src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
>      private ObjectMapper objectMapper;
이렇게 그냥 두면 null 객체일거 같은데 잘 작동할까요...?
@RequiredArgsConstructor를 통해 작동하지 않을 것 같습니다.

2023-03-30 16:44 UTC, bluayer commented on src/main/java/org/sopt/app/application/user/UserService.java
> +    }
해당 코드에는 두 가지 문제점이 있습니다.
1. int로 타입 강제를 함. -> 반올림을 하고 싶으셨던 거라면 round와 같은 메소드를 사용하여 의미를 선사하는 것이 맞습니다. 타입 강제로 인한 이슈는 부동 소수점을 다룰 때 늘 이슈가 될 수 있으므로 좋지 못합니다.
2. new String을 사용함. 차라리 +를 사용하는 것이 나은데요, 이 이유는 찾아보고 어진님을 위해 꼭 댓글로 달아주시길 바랍니다.

2023-03-30 17:20 UTC, ozzing commented on src/main/java/org/sopt/app/application/user/UserService.java
> +    }
1. 넵 변경하겠습니다.
2. new String 사용 시 아예 새로운 메모리에 할당되고 연산 과정에서 속도 저하가 있는 것으로 알고 있습니다. 유저 가입시에만 실행되는 간단한 문자열이라 신경쓰지 못했는데, +를 사용하면 좋을 것 같네요! 감사합니다.

2023-03-31 19:52 UTC, dragontaek-lee commented on src/main/java/org/sopt/app/application/auth/JwtTokenService.java
> +                .signWith(SignatureAlgorithm.HS256,
제가 알기로는 .signWith()가 deprecated 된거로 알고 있습니당! 
```
public abstract JwtBuilder signWith( java.security.Key key,
    io.jsonwebtoken.SignatureAlgorithm alg )
```
다음과 같이 인자가 변경되어 있어요.

2023-04-03 12:41 UTC, ozzing commented on src/main/java/org/sopt/app/application/auth/JwtTokenService.java
> +                .signWith(SignatureAlgorithm.HS256,
오 감사합니다!